name: Auto-merge PRs

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
