name: Auto-approve PR

on:
  pull_request_target:
    types: [opened, synchronize]


jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge "$PR_URL" --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}